### ISSUE TITLE
Topic names overridden with multiple robots

### ISSUE THREAD

**Issue by micpalmia** [micpalmia/youbot_ros_tools#7]
The topic namespace `/youbot` is used. The namespace should be set to be the name of the robot as passed from command line.

As a side problem, the teleop program will have to receive the robot name as a parameter.

Error is

```
[ERROR] [1379063684.195716525, 0.422000000]: Tried to advertise a service that is already advertised in this node [/youbot/controller_manager/reload_controller_libraries]
```

**Comment by micpalmia** [comment]
It is impossible to solve this issue in Groovy at the moment, as the namespace functionality of the launch files is commented out in the source ROS code. According to [this question](http://answers.gazebosim.org/question/4190/how-do-you-run-multiple-hector_quadrotors-without/) and answer, it's possible to solve the issue in hydro.

I'll solve as soon as I switch to ROS Hydro.

**Comment by ghost** [comment]
Just to let you know, I'm successfully running this package with Hydro.

**Comment by micpalmia** [comment]
Wonderful, didn't want to bother you sending an email. 
I'm making the switch right now.
